apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vksjob-ocp
rules:
- apiGroups:
  - "route.openshift.io"
  resources:
  - routes
  verbs:
  - get
  - list
  - create
  - delete
  - watch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vksjob-ocp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vksjob-ocp
subjects:
- kind: ServiceAccount
  name: vksjob
  namespace: default