#!/bin/bash

PROJECT_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/../.. && pwd )"

USE_KIND="${USE_KIND:-true}"

VKS_NAME=vks
VKS_HOME=${PROJECT_HOME}/.${VKS_NAME}
DB_RELEASE_NAME=mypsql
VKS_NS=${VKS_NAME}-system
KIND_CLUSTER_NAME=vkshost
KIND_CLUSTER_NODEPORT=31433
API_SERVER_PORT=7443

