#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

USE_KIND="${USE_KIND:-true}"

VKS_NAME="${VKS_NAME:-vks1}"
VKS_HOME=${SCRIPT_DIR}/.${VKS_NAME}
DB_RELEASE_NAME=mypsql
VKS_NS=${VKS_NAME}-system
VKSDB_NS=vks-system
KIND_CLUSTER_NAME=vkshost
POSTGRES_CHART_VERSION="${POSTGRES_CHART_VERSION:-11.1.5}"
KIND_CLUSTER_NODEPORT1=31433
KIND_CLUSTER_NODEPORT2=31434
KIND_CLUSTER_NODEPORT3=31435
KIND_CLUSTER_NODEPORT4=31436
KIND_CLUSTER_NODEPORT5=31437
KIND_CLUSTER_NODEPORT6=31438

# TODO - temporary hack for limitation with nodeports on kind
if [ "$VKS_NAME" == "vks1" ]; then
    KIND_CLUSTER_NODEPORT=$KIND_CLUSTER_NODEPORT1
    FLOTTA_NODEPORT=$KIND_CLUSTER_NODEPORT2
    API_SERVER_PORT=7443
elif [ "$VKS_NAME" == "vks2" ]; then
    KIND_CLUSTER_NODEPORT=$KIND_CLUSTER_NODEPORT3
    FLOTTA_NODEPORT=$KIND_CLUSTER_NODEPORT4
    API_SERVER_PORT=7444
elif [ "$VKS_NAME" == "vks3" ]; then
    KIND_CLUSTER_NODEPORT=$KIND_CLUSTER_NODEPORT5
    FLOTTA_NODEPORT=$KIND_CLUSTER_NODEPORT6
    API_SERVER_PORT=7445
else
    echo "name must be one of {'vks1','vks2','vks3'}"
    exit -127    
fi        

