#!/bin/bash
# Config the env variables for the demo

export EXTERNAL_IP=18.221.76.241
export DEPLOY_FLOTTA=true
VKS_HOST_CTX=kind-vkshost
START_CLEAN="${START_CLEAN:-false}"
DELETE_PODMAN_AGENTS="${DELETE_PODMAN_AGENTS:-false}"
SSH_CLUSTERS="ssh ubuntu@18.188.59.138"
SSH_PODMAN1="ssh fedora@3.135.197.148"
SSH_PODMAN2="ssh fedora@18.117.103.14"
DB_RELEASE_NAME=mypsql
VKSDB_NS=vks-system









