#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
HOME_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/../.. && pwd )"

source ${SCRIPT_DIR}/config
source ${SCRIPT_DIR}/demo-magic

TYPE_SPEED=30
#PROMPT_AFTER=1
DEMO_PROMPT="\U0001F4F3 ${1}> "

function pause() {
  if [[ -n "${NO_WAIT}" ]]; then
    sleep 2
  else
    if [[ -n "${1-}" ]]; then
      sleep "$1"
    else
      wait
    fi
  fi
}

END=false
function end() {
  END=true
}
trap end SIGINT

pe "podman pod ls"
pe "systemctl status cymba.service --lines=0"
pe "systemctl status ocm-registration --lines=0"
pe "systemctl status ocm-work --lines=0"

pause

pe "podman pod ls"

wait